### ISSUE TITLE
Implement data section functionality

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/highcharts-editor#5]
## Description
Implement functionality to import CSV data from file upload as well as from manually cutting and pasting tabular data (in CSV format with comma as delimiter?). Refer to the UI/UX team's mockups on Figma: https://www.figma.com/design/4GXcYsMq3xbLNcX1R9HBZO/RAMP-Storylines-Editor-Wireframes?node-id=1451-1867&node-type=canvas&t=bHRmRPAlZ6DmltpP-0

## TODO
- [ ] add a drop and drop file upload zone (follow styling to image/video editor in RESPECT)
- [ ] add an import existing chart option as placeholder for now (to upload a fully configured highcharts configuration file)
- [ ] add an option to paste in formatted data
